name: CI Jest Tests
on: [push, pull_request]
jobs:
  build:
    name: ci_jest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test
